#! /bin/sh

set -e

for dir in /var/run/rendermq /var/log/rendermq; do
    if dpkg-statoverride --list $dir >/dev/null 2>&1; then
        dpkg-statoverride --remove $dir
        rmdir --ignore-fail-on-non-empty $dir
    fi
done

#DEBHELPER#
