#!/bin/sh
#
#  rendermq-run-worker
#

LOGDIR=/var/log/rendermq

exec >$LOGDIR/worker-$$.log 2>&1

export PYTHONPATH=/usr/lib/rendermq/pythonlibs

while true; do
    echo "Starting worker.py..."
    /usr/lib/rendermq/worker/worker.py $*
    sleep 1
done

